# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-24 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favoriteinformation',
            fields=[
                ('favorite_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'favoriteinformation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movieinformation',
            fields=[
                ('movie_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=50)),
                ('movie_year', models.CharField(blank=True, max_length=5, null=True)),
                ('movie_director', models.CharField(blank=True, max_length=50, null=True)),
                ('movie_screenwriter', models.CharField(blank=True, max_length=50, null=True)),
                ('movie_roles', models.CharField(blank=True, max_length=250, null=True)),
                ('movie_style', models.CharField(blank=True, max_length=50, null=True)),
                ('movie_country', models.CharField(blank=True, max_length=15, null=True)),
                ('movie_language', models.CharField(blank=True, max_length=20, null=True)),
                ('movie_date', models.CharField(blank=True, max_length=30, null=True)),
                ('movie_long', models.CharField(blank=True, max_length=10, null=True)),
                ('movie_imdb', models.CharField(blank=True, max_length=15, null=True)),
                ('movie_evaluation', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'movieinformation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Surfinformation',
            fields=[
                ('surf_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'surfinformation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userinformation',
            fields=[
                ('user_name', models.CharField(max_length=25)),
                ('user_account', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=20)),
                ('user_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('user_email', models.CharField(blank=True, max_length=20, null=True)),
                ('user_sex', models.CharField(blank=True, max_length=10, null=True)),
                ('user_hobby', models.CharField(blank=True, max_length=255, null=True)),
                ('user_age', models.IntegerField(blank=True, null=True)),
                ('user_createtime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'userinformation',
                'managed': False,
            },
        ),
    ]
