# Generated by Django 3.2.13 on 2022-06-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registerinfo',
            fields=[
                ('user_account', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=25)),
                ('user_password', models.CharField(max_length=20)),
                ('user_phone', models.CharField(max_length=15)),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'registerinfo',
                'managed': False,
            },
        ),
    ]
