# Generated by Django 3.2.13 on 2022-07-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRApp', '0003_scoreinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moviecomments',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('movie_name', models.CharField(blank=True, max_length=50, null=True)),
                ('user_name', models.CharField(blank=True, max_length=20, null=True)),
                ('evaluation', models.CharField(blank=True, max_length=10, null=True)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('up', models.CharField(blank=True, max_length=5, null=True)),
                ('down', models.CharField(blank=True, max_length=5, null=True)),
                ('response', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'moviecomments',
                'managed': False,
            },
        ),
    ]
